baseURL = 'https://devimahatmyam.aurobharati.in/'
languageCode = 'en-us'
title = 'DEVIMAHATMYAM'
theme = "hugo-flex"
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
  description = "Explore the Devīmāhātmyam — a sacred scripture dedicated to the Divine Mother."

[menu]

  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "About Us"
  url = ""   
  weight = 2
  identifier = "About"  

  [[menu.main]]
  name = "Sri Aurobindo "
  url = "/sri-aurobindo/"
  parent = "About"
  weight = 1

  [[menu.main]]
  name = "The Mother"
  url = "/the-mother/"
  parent = "About"
  weight = 2

  [[menu.main]]
  name = "Sri Aurobindo Society  "
  url = "/sri-aurobindo-society/"
  parent = "About"
  weight = 3

  [[menu.main]]
  name = "AuroBharati"
  url = "/aurobharati/"
  parent = "About"
  weight = 4

  [[menu.main]]
  name = "About the Project"
  url = "/about-the-project/"
  parent = "About"
  weight = 5

  [[menu.main]]
  name = "Acknowledgement"
  url = "/acknowledgement/"
  parent = "About"
  weight = 6

  [[menu.main]]
  name = "Śaktitattvam"
  url = ""
  weight = 3
  identifier = "Śaktitattvam"  

  [[menu.main]]
  name = "Sri Aurobindo  and The Mother on Śaktitattvam"
  url = "/sri-aurobindo-and-the-mother-on-saktitattvam/"
  parent = "Śaktitattvam"
  weight = 1

  [[menu.main]]
  name = "Hymn to Durgā by Sri Aurobindo"
  url = "/hymn-to-durga-by-sri-aurobindo/"
  parent = "Śaktitattvam"
  weight = 2

  [[menu.main]]
  name = "The Mother by Sri Aurobindo "
  url = "/the-mother-book-by-sri-aurobindo/"
  parent = "Śaktitattvam"
  weight = 3

  [[menu.main]]
  name = "The Worship of Devi by T V Kapali Sastri"
  url = "/the-worship-of-devi-by-t-v-kapali-sastri/"
  parent = "Śaktitattvam"
  weight = 4

  [[menu.main]]
  name = "Devimāhātmyam"
  url = "/devimahatmyam/"
  weight = 4

  [[menu.main]]
  name = "Publications"
  url = "https://aurobharati.in/publications/"
  weight = 5
  identifier = "Resources"
  [menu.main.params]
  target = "_blank"
  
  [[menu.main]]
  name = "Program"
  url = "https://aurobharati.in/category/past-events/"
  weight = 6
  [menu.main.params]
  target = "_blank"

  [[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 7

paginate = 2